// Matthew RIchter 
// MIU - Full Sail University
// Project 3
// May 15, 2012
var json = {
	"project1":		{
		"project":		["Project Type:", "Kitchen"],
		"pname":		["Project Name:", "Richter Kitchen"],
		"fname":		["First Name:", "Matthew"],
		"lname": 		["Last Name:", "Richter"],
		"email":			["Email:", "matt@gorichter.com"],
		"phone":			["Phone:", "9085006304"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "high"],
		"priority":		["Priority:", "9"],
		"startDate"	:	["Start Date:", "2012-5-1"],
		"jobNotes":		["Job Notes:", "Re-due tile floor and add three new custom cabinets"]
	},
	"project2":		{
		"project":		["Project Type:", "Addition"],
		"pname":		["Project Name:", "Anderson Addition"],
		"fname":		["First Name:", "Chris"],
		"lname": 		["Last Name:", "Anderson"],
		"email":			["Email:", "chris@anderson.com"],
		"phone":			["Phone:", "4075006304"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "medium"],
		"priority":		["Priority:", "7"],
		"startDate":	["Start Date:", "2012-6-1"],
		"jobNotes":		["Job Notes:", "600 sq ft addition of the family room"]
	},
	"project3":		{
		"project":		["Project Type:", "Lavatory"],
		"pname":		["Project Name:", "Richter Lavatory"],
		"fname":		["First Name:", "Matthew"],
		"lname": 		["Last Name:", "Richter"],
		"email":			["Email:", "matt@gorichter.com"],
		"phone":			["Phone:", "9085006304"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "high"],
		"priority":		["Priority:", "9"],
		"startDate"	:	["Start Date:", "2012-5-1"],
		"jobNotes":		["Job Notes:", "Place new face-frame on the vanity and remove bench seat in shower and re-tile"]
	},
	"project4":		{
		"project":		["Project Type:", "Roof"],
		"pname":		["Project Name:", "Stokes Roof"],
		"fname":		["First Name:", "Bryan"],
		"lname": 		["Last Name:", "Stokes"],
		"email":			["Email:", "bryan@SB.com"],
		"phone":			["Phone:", "9086542727"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "medium"],
		"priority":		["Priority:", "8"],
		"startDate"	:	["Start Date:", "2012-7-1"],
		"jobNotes":		["Job Notes:", "Take off existing two layers and repair any rotten wood"]
	},
	"project5":		{
		"project":		["Project Type:", "Basement"],
		"pname":		["Project Name:", "Jones Basement"],
		"fname":		["First Name:", "Travis"],
		"lname": 		["Last Name:", "Jones"],
		"email":			["Email:", "traivs@jones.com"],
		"phone":			["Phone:", "9088393933"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "low"],
		"priority":		["Priority:", "4"],
		"startDate"	:	["Start Date:", "2012-6-1"],
		"jobNotes":		["Job Notes:", "finish similar to the McKensie job"]
	},
	"project6":		{
		"project":		["Project Type:", "Addition"],
		"pname":		["Project Name:", "Trivella Addition"],
		"fname":		["First Name:", "Adrienne"],
		"lname": 		["Last Name:", "Trivella"],
		"email":			["Email:", "ade@trivella.com"],
		"phone":			["Phone:", "9086372524"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "high"],
		"priority":		["Priority:", "8"],
		"startDate"	:	["Start Date:", "2012-5-1"],
		"jobNotes":		["Job Notes:", "400 square feet off the kitchen, tile floor anderson windows, match exterior"]
	},
	"project7":		{
		"project":		["Project Type:", "Addition"],
		"pname":		["Project Name:", "Oraschin Addition"],
		"fname":		["First Name:", "David"],
		"lname": 		["Last Name:", "Oraschin"],
		"email":			["Email:", "dave@oraschin.com"],
		"phone":			["Phone:", "9086270412"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "high"],
		"priority":		["Priority:", "10"],
		"startDate"	:	["Start Date:", "2012-7-1"],
		"jobNotes":		["Job Notes:", "blow out family room wall and add 600 square foot great room, match exterior"]
	},
	"project8":		{
		"project":		["Project Type:", "Lavatory"],
		"pname":		["Project Name:", "Mantes Lavatory"],
		"fname":		["First Name:", "Gerry"],
		"lname": 		["Last Name:", "Mantes"],
		"email":			["Email:", "gerry@mantes.com"],
		"phone":			["Phone:", "9081232930"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "high"],
		"priority":		["Priority:", "7"],
		"startDate"	:	["Start Date:", "2012-7-1"],
		"jobNotes":		["Job Notes:", "new toilet, bath tub, vanity and shower"]
	},
	"project9":		{
		"project":		["Project Type:", "Lavatory"],
		"pname":		["Project Name:", "Smith Lavatory"],
		"fname":		["First Name:", "John"],
		"lname": 		["Last Name:", "Smith"],
		"email":			["Email:", "john@smith.com"],
		"phone":			["Phone:", "9082549986"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "low"],
		"priority":		["Priority:", "6"],
		"startDate"	:	["Start Date:", "2012-8-1"],
		"jobNotes":		["Job Notes:", "New shower tile and floor"]
	},
	"project10":	{
		"project":		["Project Type:", "Roof"],
		"pname":		["Project Name:", "Roth Roof"],
		"fname":		["First Name:", "Joe"],
		"lname": 		["Last Name:", "Roth"],
		"email":			["Email:", "joe@roth.com"],
		"phone":			["Phone:", "9085317283"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "high"],
		"priority":		["Priority:", "6"],
		"startDate"	:	["Start Date:", "2012-9-1"],
		"jobNotes":		["Job Notes:", "Roof over existing roof no dumpster required"]
	},
	"project11":	{
		"project":		["Project Type:", "Lavatory"],
		"pname":		["Project Name:", "Stires Lavatory"],
		"fname":		["First Name:", "Kim"],
		"lname": 		["Last Name:", "Stires"],
		"email":			["Email:", "kim@wfb.com"],
		"phone":			["Phone:", "9084737272"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "high"],
		"priority":		["Priority:", "8"],
		"startDate"	:	["Start Date:", "2012-8-1"],
		"jobNotes":		["Job Notes:", "Gut the entire bathroom and replace everything"]
	},
	"project12":	{
		"project":		["Project Type:", "Addition"],
		"pname":		["Project Name:", "Papio Addition"],
		"fname":		["First Name:", "Matthew"],
		"lname": 		["Last Name:", "Papio"],
		"email":			["Email:", "matt@papio.com"],
		"phone":			["Phone:", "9736473829"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "high"],
		"priority":		["Priority:", "7"],
		"startDate"	:	["Start Date:", "2012-6-1"],
		"jobNotes":		["Job Notes:", "new floor, vanity and bath"]
	},
	"project13":	{
		"project":		["Project Type:", "Basement"],
		"pname":		["Project Name:", "Richter Basement"],
		"fname":		["First Name:", "James"],
		"lname": 		["Last Name:", "Dill"],
		"email":			["Email:", "james@dill.com"],
		"phone":			["Phone:", "9732781166"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "high"],
		"priority":		["Priority:", "5"],
		"startDate"	:	["Start Date:", "2012-10-1"],
		"jobNotes":		["Job Notes:", "finish entire basement sheetrock and tile floor with built-ins"]
	},
	"project14":	{
		"project":		["Project Type:", "Basement"],
		"pname":		["Project Name:", "Kelly Basement"],
		"fname":		["First Name:", "Jeff"],
		"lname": 		["Last Name:", "Kelly"],
		"email":			["Email:", "jeff@kelly.com"],
		"phone":			["Phone:", "9084738383"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "medium"],
		"priority":		["Priority:", "5"],
		"startDate"	:	["Start Date:", "2012-11-1"],
		"jobNotes":		["Job Notes:", "wine closet and sheetrock with cork floor"]
	},
	"project15":	{
		"project":		["Project Type:", "Lavatory"],
		"pname":		["Project Name:", "Richdale Lavatory"],
		"fname":		["First Name:", "John"],
		"lname": 		["Last Name:", "Richdale"],
		"email":			["Email:", "john@richdale.com"],
		"phone":			["Phone:", "9734920098"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "high"],
		"priority":		["Priority:", "4"],
		"startDate"	:	["Start Date:", "2012-12-1"],
		"jobNotes":		["Job Notes:", "gut entire bathroom new everything with built-in tile shower and new vanity"]
	},
	"project16":	{
		"project":		["Project Type:", "Roof"],
		"pname":		["Project Name:", "Hollis Roof"],
		"fname":		["First Name:", "Link"],
		"lname": 		["Last Name:", "Hollis"],
		"email":			["Email:", "link@hollis.com"],
		"phone":			["Phone:", "9085006304"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "medium"],
		"priority":		["Priority:", "9"],
		"startDate"	:	["Start Date:", "2012-7-1"],
		"jobNotes":		["Job Notes:", "Tear off existing roof replace rotten wood + new gutters"]
	},
	"project17":	{
		"project":		["Project Type:", "Kitchen"],
		"pname":		["Project Name:", "Stires Kitchen"],
		"fname":		["First Name:", "Pete"],
		"lname": 		["Last Name:", "Stires"],
		"email":			["Email:", "pete@stires.com"],
		"phone":			["Phone:", "9087776253"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "high"],
		"priority":		["Priority:", "9"],
		"startDate"	:	["Start Date:", "2012-6-1"],
		"jobNotes":		["Job Notes:", "all new cabinets conestoga doors and custom island"]
	},
	"project18":	{
		"project":		["Project Type:", "Kitchen"],
		"pname":		["Project Name:", "Mathis Kitchen"],
		"fname":		["First Name:", "Michael"],
		"lname": 		["Last Name:", "Mathis"],
		"email":			["Email:", "mike@mathis.com"],
		"phone":			["Phone:", "9087223314"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "high"],
		"priority":		["Priority:", "4"],
		"startDate"	:	["Start Date:", "2012-11-1"],
		"jobNotes":		["Job Notes:", "all new cabinets and wine rack and tile floor"]
	},
	"project19":	{
		"project":		["Project Type:", "Kitchen"],
		"pname":		["Project Name:", "Long Kitchen"],
		"fname":		["First Name:", "Tom"],
		"lname": 		["Last Name:", "Long"],
		"email":			["Email:", "tom@long.com"],
		"phone":			["Phone:", "9083764737"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "medium"],
		"priority":		["Priority:", "7"],
		"startDate"	:	["Start Date:", "2012-8-1"],
		"jobNotes":		["Job Notes:", "new doors and paint job"]
	},
	"project20":	{
		"project":		["Project Type:", "Roof"],
		"pname":		["Project Name:", "Monica Roof"],
		"fname":		["First Name:", "James"],
		"lname": 		["Last Name:", "Monica"],
		"email":			["Email:", "james@monica.com"],
		"phone":			["Phone:", "9089874232"],
		"emailOkay":	["Communicate via email:", "Yes"],
		"cost":			["Price per square foot:", "high"],
		"priority":		["Priority:", "9"],
		"startDate"	:	["Start Date:", "2012-6-1"],
		"jobNotes":		["Job Notes:", "Remove old roof & gutters"]
	}
}